#! /bin/sh
### BEGIN INIT INFO
# Provides:          config_interruption
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Lab 05.
# Description:       Configures GPIO for Lab 05.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "Galileo")
    if [ ! -d /sys/class/gpio/gpio30 ] ; then
	    echo -n "30" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio30/direction
	echo -n "0" > /sys/class/gpio/gpio30/value
	
	if [ ! -d /sys/class/gpio/gpio15 ] ; then
	    echo -n "15" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio15/direction
	echo -n "rising" > /sys/class/gpio/gpio15/edge
	chgrp gpio /sys/class/gpio/gpio15/edge
	chmod g+rw /sys/class/gpio/gpio15/edge
	chgrp gpio /sys/class/gpio/gpio15/value
	chmod g+r /sys/class/gpio/gpio15/value
    	;;
    esac
    ;;
  stop)
    case $boardId in
      "Galileo")
	echo -n "1" > /sys/class/gpio/gpio30/value
  echo -n "30" > /sys/class/gpio/unexport
  echo -n "none" > /sys/class/gpio/gpio15/edge
	echo -n "15" > /sys/class/gpio/unexport
    	;;
    esac
    ;;
  status)
    ls -d /sys/class/gpio/gpio*
    ;;
  *)
    echo -n "Usage: $0 " 
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
