#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032lab03_1
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Lab 03.
# Description:       Configures GPIO for Lab 03.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "Galileo")
      	if [ ! -d /sys/class/gpio/gpio55 ] ; then
	    echo -n "55" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio55/direction
	echo -n "1" > /sys/class/gpio/gpio55/value
	
	if [ ! -d /sys/class/gpio/gpio39 ] ; then
	    echo -n "39" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio39/direction
	echo -n "strong" > /sys/class/gpio/gpio39/drive
	chgrp gpio /sys/class/gpio/gpio39/value
	chmod g+rw /sys/class/gpio/gpio39/value
	
	# IO13 LED is not mounted. Use the one at gpio3
	if [ ! -d /sys/class/gpio/gpio3 ] ; then
	    echo -n "3" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio3/direction
	chgrp gpio /sys/class/gpio/gpio3/value
	chmod g+rw /sys/class/gpio/gpio3/value
    	;;
      "GalileoGen2")
	if [ ! -d /sys/class/gpio/gpio46 ] ; then
	    echo -n "46" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio46/direction
	echo -n "0" > /sys/class/gpio/gpio46/value
	
	if [ ! -d /sys/class/gpio/gpio30 ] ; then
	    echo -n "30" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio30/direction
	echo -n "0" > /sys/class/gpio/gpio30/value

	if [ ! -d /sys/class/gpio/gpio7 ] ; then
	    echo -n "7" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio7/direction
	chgrp gpio /sys/class/gpio/gpio7/value
	chmod g+rw /sys/class/gpio/gpio7/value
	;;
    esac
    ;;
  stop)
    case $boardId in
      "Galileo")
    	echo -n "in" > /sys/class/gpio/gpio39/direction
    	echo -n "39" > /sys/class/gpio/unexport
	echo -n "55" > /sys/class/gpio/unexport
	echo -n "3" > /sys/class/gpio/unexport
    	;;
      "GalileoGen2")
    	echo -n "in" > /sys/class/gpio/gpio7/direction
    	echo -n "7" > /sys/class/gpio/unexport
    	echo -n "1" > /sys/class/gpio/gpio30/value
	echo -n "30" > /sys/class/gpio/unexport
	echo -n "46" > /sys/class/gpio/unexport
	;;
    esac
    ;;
  status)
    ls -d /sys/class/gpio/gpio*
    ;;
  *)
    echo -n "Usage: $0 " 
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
