#! /bin/sh
### BEGIN INIT INFO
# Provides:          config_push_buzzer
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for buzzer controlled by push button.
# Description:       Configures GPIO for input interrupts in IO2 and output in IO3.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "Galileo")
  if [ ! -d /sys/class/gpio/gpio31 ] ; then
      echo -n "31" > /sys/class/gpio/export
  fi
  echo -n "out" > /sys/class/gpio/gpio31/direction
  echo -n "0" > /sys/class/gpio/gpio31/value

  if [ ! -d /sys/class/gpio/gpio14 ] ; then
      echo -n "14" > /sys/class/gpio/export
  fi
  echo -n "in" > /sys/class/gpio/gpio14/direction
  echo -n "rising" > /sys/class/gpio/gpio14/edge
  chgrp gpio /sys/class/gpio/gpio14/edge
  chmod g+rw /sys/class/gpio/gpio14/edge
  chgrp gpio /sys/class/gpio/gpio14/value
  chmod g+r /sys/class/gpio/gpio14/value
  
  if [ ! -d /sys/class/gpio/gpio30 ] ; then
	    echo -n "30" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio30/direction
	echo -n "1" > /sys/class/gpio/gpio30/value

  if [ ! -d /sys/class/gpio/gpio18 ] ; then
      echo -n "18" > /sys/class/gpio/export
  fi
  echo -n "out" > /sys/class/gpio/gpio18/direction
  echo -n "strong" > /sys/class/gpio/gpio18/drive
  chgrp gpio /sys/class/gpio/gpio18/value
  chmod g+rw /sys/class/gpio/gpio18/value
    	;;
    esac
    ;;
  stop)
    case $boardId in
      "Galileo")
	echo -n "1" > /sys/class/gpio/gpio31/value
  echo -n "31" > /sys/class/gpio/unexport
  echo -n "none" > /sys/class/gpio/gpio14/edge
	echo -n "14" > /sys/class/gpio/unexport
  echo -n "30" > /sys/class/gpio/unexport
  echo -n "18" > /sys/class/gpio/unexport
    	;;
    esac
    ;;
  status)
    ls -d /sys/class/gpio/gpio*
    ;;
  *)
    echo -n "Usage: $0 " 
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
