#! /bin/sh
### BEGIN INIT INFO
# Provides:          config_pwm_led
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Lab 06.
# Description:       Configures GPIO for Lab 06.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "Galileo")
    if [ ! -d /sys/class/gpio/gpio30 ] ; then
	    echo -n "30" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio30/direction
	echo -n "1" > /sys/class/gpio/gpio30/value
	
	if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
		echo -n "3" > /sys/class/pwm/pwmchip0/export
	fi

	chgrp pwm /sys/class/pwm/pwmchip0/pwm3/period
	chgrp pwm /sys/class/pwm/pwmchip0/pwm3/enable
  chgrp pwm /sys/class/pwm/pwmchip0/pwm3/duty_cycle
  chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
	chmod g+rw /sys/class/pwm/pwmchip0/pwm3/period
	chmod g+rw /sys/class/pwm/pwmchip0/pwm3/enable
  chmod g+rw /sys/class/pwm/pwmchip0/pwm3/duty_cycle
	chmod g+rw /sys/class/pwm/pwmchip0/device/pwm_period
    ;;
    esac
    ;;
  stop)
    case $boardId in
      "Galileo")
	echo -n "0" > /sys/class/pwm/pwmchip0/pwm3/enable
    echo -n "3" > /sys/class/pwm/pwmchip0/unexport
	echo -n "30" > /sys/class/gpio/unexport
	;;
    esac
    ;;
  status)
    echo -n Period:
    case $boardId in
      "Galileo")
        cat /sys/class/pwm/pwmchip0/pwm3/period
        ;;
    esac
    echo -n Duty Cicle:
    cat /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    echo -n Enable:
    cat /sys/class/pwm/pwmchip0/pwm3/enable
    ;;
  *)
    echo -n "Usage: $0 " 
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
